spring.datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/laa_pds_forms
    username: pds
    password: password
spring.jpa:
  properties:
    hibernate:
      temp.use_jdbc_metadata_defaults: false    
